---
- fail:
    msg: "No UMD major release defined. Please use 'release' variable."
  when: release is not defined

- include_vars: ../defaults/main.yml

- name: Deploy Debian-specific
  include: debian.yml
  when: (ansible_distribution == "Debian") and (release == "3")

- name: Deploy RedHat-specific
  include: redhat.yml
  when: (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS") or (ansible_distribution == "Scientific")

- name: Download verification repository files
  get_url: url={{ item }} dest={{ sources_dir }}
  with_items: 
    - "{{ verification_repofile|default([]) }}"
  when: verification_repofile is defined

- name: Set up IGTF repository
  include: igtf.yml
