---

- name: Download and install release package (RedHat)
  yum: name={{ release_url[release] }} state=present

- name: Add UMD base candidate repository
  yum_repository:
    name: "UMD-{{ release }}-candidate-base"
    description: "UMD-{{ release }} candidate - base"
    file: "UMD-{{ release }}-candidate"
    baseurl: "http://repository.egi.eu/sw/production/umd/candidate/{{ release }}/{{ nick }}/x86_64/base" 
    protect: yes
    enabled: yes
    priority: 1
    gpgcheck: no
  when: enable_candidate_repo

- name: Add UMD updates candidate repository
  yum_repository:
    name: "UMD-{{ release }}-candidate-updates"
    description: "UMD-{{ release }} candidate - updates"
    file: "UMD-{{ release }}-candidate"
    baseurl: "http://repository.egi.eu/sw/production/umd/candidate/{{ release }}/{{ nick }}/x86_64/updates" 
    protect: yes
    enabled: yes
    priority: 1
    gpgcheck: no
  when: enable_candidate_repo

- name: Enable UMD testing repository
  command: yum-config-manager --enable UMD-*-testing
  when: enable_testing_repo

- name: Enable UMD untested repository
  command: yum-config-manager --enable UMD-*-untested
  when: enable_untested_repo
